//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImenikSem.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontakt
    {
        public int Id { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public int Korisnik_id { get; set; }
        public string Broj { get; set; }
        public Nullable<int> BrojPregleda { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
    }
}
